language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
    - os: osx
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121
      mono: none

script:
  - dotnet restore src
  - dotnet test src/Intelecom.SmsGateway.Client.Tests